name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: chmod
      run: chmod +x ./gradlew
      
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Make zip file
      run: zip -r ./practice-deploy.zip .
      shell: bash

    - name: view file
      run: ls -l ./practice-deploy.zip

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1

      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./practice-deploy.zip s3://donation-webtoon/practice-deploy.zip

    - name: Code Deploy
      run: >
        aws deploy create-deployment --application-name CodeDeployGitHubDemo-App 
        --deployment-config-name CodeDeployDefault.AllAtOnce
        --deployment-group-name CodeDeployGitHubDemo-DepGrp
        --s3-location bucket=donation-webtoon,bundleType=zip,key=practice-deploy.zip
